global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'node_red_metrics'
    static_configs:
      - targets: ['localhost:1880']

  - job_name: 'mqtt_exporter'
    static_configs:
      - targets: ['localhost:9399']
